### PR TITLE
Just updated my email and organization in parent pom

### PR DESCRIPTION
**Pull request by LorenzoBettini**
Signed-off-by: Lorenzo Bettini <lorenzo.bettini@gmail.com>

### CODE REVIEW

**Comment by cdietrich** [comment]
@LorenzoBettini are you going to do prs against all the other repos too e.g. *developers.gradle
@ArneDeutsch are you going to do prs to add you names to these files?
maybe it can be done in one step

**Comment by cdietrich** [comment]
at least these files may need to be updated
```
./xtext-web/gradle/developers.gradle
./xtext-maven/org.eclipse.xtext.maven.parent/pom.xml
./xtext-core/gradle/developers.gradle
./xtext-idea/gradle/developers.gradle
./xtext-extras/gradle/developers.gradle
./xtext-xtend/releng/org.eclipse.xtend.maven.parent/pom.xml
./xtext-xtend/gradle/developers.gradle
./xtext-lib/gradle/developers.gradle
```

**Comment by LorenzoBettini** [comment]
Oh, I never realized that... I'll update them too then
but I would skip the idea one, OK?

**Comment by cdietrich** [comment]
the idea code is just there "as is". you can skip it if you want. there were no releases since 2.10

**Comment by ArneDeutsch** [comment]
I will add my data to the gradle and maven files.

**Pull request merged**
