### PR TITLE
fixed bogus pom structure #14

### PR DESCRIPTION
**Pull request by cdietrich**
fixed bogus pom structure #14
Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by cdietrich** [comment]
please review

**Comment by kthoms** [comment]
Hmm, why not keeping the pom.xml in the root dir and making that to the parent project?

**Comment by cdietrich** [comment]
cause i have no idea how i shall move the deploy stuff arround

**Comment by kthoms** [comment]
@dhuebner your meaning?

**Comment by dhuebner** [comment]
@kthoms I didn't get the "totally bogus" part from #14 :-/
Also not sure how it will impact the deployment scripts. 
What I would definitely remove is the lifecycle mapping entry!

**Comment by cdietrich** [comment]
the parent is the parent of its parent

**Comment by dhuebner** [comment]
@cdietrich One is probably the modules parent and the other is configuration parent.
However, if it still works, I don't really care

**Pull request merged**
