### PR TITLE
added support for polulating platform resource map

### PR DESCRIPTION
**Pull request by cdietrich**

### CODE REVIEW

**Comment by cdietrich** [comment]
@janhicken @kthoms @szarnekow

i took @janhicken initial pull request and added to possiblility to opt in into the autofil as well as to give an explicit mapping

**Comment by cdietrich** [comment]
p.s: i have to rebase to get stuff running.
and this breaks the ip validation
=> we need to make this two step if we want to get this way.

**Comment by cdietrich** [comment]
@janhicken could you rebase your original pr on master so that i dont have?

**Comment by janhicken** [comment]
@cdietrich Done.

Thanks for your work on the feature

**Pull request closed without merging**
